version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: upscale-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - upscale-network

  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: https://xlr8.online/api
    container_name: upscale-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - upscale-network

# Define the network here
networks:
  upscale-network:
    driver: bridge
